MAINT: Changes based on review

diff --git a/copyright_check b/copyright_check
--- a/copyright_check
+++ b/copyright_check
@@ -1,5 +1,27 @@
 #!/bin/bash
-# Call copyright_check with 1 or more filepath arguments to check.
+
+show_help() {
+    echo "info: Check the copyright header in the specified files."
+    echo "    If the non-empty file does not contain the copyright header, it "
+    echo "    will be added. If a file looks like it does contain a copyright "
+    echo "    header, it will verified that it matches exactly."
+    echo "    Hash bangs are preserved."
+    echo ''
+    echo "usage: $0 FILEPATH..."
+    echo ''
+    echo 'positional arguments:'
+    echo '  FILEPATH...    The file(s) to check'
+    echo ""
+    echo "options:"
+    echo "  -h|--help     Show this help message and exit"
+    echo ""
+}
+
+if [[ " $@ " =~ " --help " || " $@ " =~ " -h " ]]; then
+    show_help
+    exit 0
+fi
+
 
 copyright_header="\
 # (C) Crown Copyright, Met Office. All rights reserved.\n\
@@ -22,6 +44,21 @@ correct_copyright() {
     python -c 'import sys; sys.exit(0 if "'"$1"'" in open("'"$2"'", "r").read() else 1)'
 }
 
+
+# Function to delete temporary files
+cleanup() {
+    for filepath in "$@"; do
+        tmp_file="${filepath}.tmp"
+        if [ -f "$tmp_file" ]; then
+            echo "Deleting temporary file: $tmp_file"
+            rm -f "$tmp_file" 2&> /dev/null
+        fi
+    done
+}
+
+# Trap the EXIT signal to call the cleanup function
+trap 'cleanup "$@"' EXIT
+
 found_error=0
 for filepath in "$@"; do
     if contains_copyright "${filepath}"; then
@@ -35,14 +72,12 @@ for filepath in "$@"; do
     elif [ -s "${filepath}" ]; then  # skip empty files
         echo "Adding missing Copyright to '${filepath}'"
         tmp_file="${filepath}.tmp"
-        rm -f ${tmp_file} 2&> /dev/null
-        touch ${tmp_file}
         if defines_hash_bang "${filepath}"; then
             head -n 1 ${filepath} > ${tmp_file}
             echo -e ${copyright_header} >> ${tmp_file}
             tail -n +2 ${filepath} >> ${tmp_file}
         else
-            echo -e ${copyright_header} >> ${tmp_file}
+            echo -e ${copyright_header} > ${tmp_file}
             cat ${filepath} >> ${tmp_file}
         fi
         mv ${tmp_file} ${filepath}
